[package]
name = "tauri-plugin-sql"
version = "2.2.0"
description = "Interface with SQL databases."
authors = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
repository = { workspace = true }
links = "tauri-plugin-sql"

[package.metadata.docs.rs]
features = ["sqlite"]
rustc-args = ["--cfg", "docsrs"]
rustdoc-args = ["--cfg", "docsrs"]

[package.metadata.platforms.support]
windows = { level = "full", notes = "" }
linux = { level = "full", notes = "" }
macos = { level = "full", notes = "" }
android = { level = "full", notes = "" }
ios = { level = "full", notes = "" }

[build-dependencies]
tauri-plugin = { workspace = true, features = ["build"] }

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
tauri = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }
# futures-core = "0.3"
# sqlx = { version = "0.8", features = ["json", "time"] }
# time = "0.3"
# tokio = { version = "1", features = ["sync"] }
rusqlite = { version = "0.31", features = ["bundled"] }
indexmap = { version = "2", features = ["serde"] }
uuid = { version = "1", features = ["v4", "serde"] }
base64 = "0.22"

[features]
default = ["sqlite"]
# sqlite = ["sqlx/sqlite", "sqlx/runtime-tokio"]
sqlite = []
# mysql = ["sqlx/mysql", "sqlx/runtime-tokio-rustls"]
# postgres = ["sqlx/postgres", "sqlx/runtime-tokio-rustls"]
# TODO: bundled-cipher etc

[dev-dependencies]
tauri = { workspace = true, features = ["test"] }
tempfile = "3.10" # Added for file DB tests
